apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   deployment.kubernetes.io/revision: "1"
  # creationTimestamp: "2020-07-19T11:32:18Z"
  # generation: 1
  labels:
    app: blue
  name: blue
  namespace: default
  # resourceVersion: "543425"
  # selfLink: /apis/apps/v1/namespaces/default/deployments/orange
  # uid: aa6db412-16aa-470e-b5b1-008b5da651f5
spec:
  # progressDeadlineSeconds: 600
  replicas: 1
  # revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      # creationTimestamp: null
      labels:
        app: blue
    spec:
      containers:
      - image: censtrom/blue-backend:v1
        imagePullPolicy: Always
        name: blue-backend
        resources: {}
      - image: censtrom/blue-nginx:v1
        imagePullPolicy: Always
        name: blue-nginx
        resources: {}
        # terminationMessagePath: /dev/termination-log
        # terminationMessagePolicy: File
      # dnsPolicy: ClusterFirst
      restartPolicy: Always
      # schedulerName: default-scheduler
      # securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  # availableReplicas: 1
  # conditions:
  # - lastTransitionTime: "2020-07-19T11:32:31Z"
  #   lastUpdateTime: "2020-07-19T11:32:31Z"
  #   message: Deployment has minimum availability.
  #   reason: MinimumReplicasAvailable
  #   status: "True"
  #   type: Available
  # - lastTransitionTime: "2020-07-19T11:32:18Z"
  #   lastUpdateTime: "2020-07-19T11:32:31Z"
  #   message: ReplicaSet "orange-56cfb8865f" has successfully progressed.
  #   reason: NewReplicaSetAvailable
  #   status: "True"
  #   type: Progressing
  # observedGeneration: 1
  # readyReplicas: 1
  replicas: 1
  # updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  # creationTimestamp: "2020-07-19T11:33:07Z"
  labels:
    app: blue
  name: blue
  namespace: default
  # resourceVersion: "543513"
  # selfLink: /api/v1/namespaces/default/services/orange
  # uid: b4db7f71-a2e9-4432-9fcb-80e319936832
spec:
  # clusterIP: 10.104.195.115
  # externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31585
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: blue
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}